language: python
python:
  - "3.7"
sudo: required
install:
  - python -m venv venv
  - source venv/bin/activate
  - pip -V
  - pip --user install pyyaml
  - pip --user install Pillow
  - python scripts/nest.py
script:
  - python -m venv venv
  - python scripts/main.py
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: master