language: python
python:
  - "3.7"
sudo: required
install:
  - python -V
  - pip -V
  - pip install --user --ignore-installed pyyaml
  - pip install --user Pillow
script:
  - python scripts/nest.py
  - python scripts/main.py
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: master